version: "3.3"
services:
  farmer:
    image: ghcr.io/subspace/farmer:gemini-2a-2022-sep-10
    command:
      - --base-path
      - /var/subspace
      - farm
      - --node-rpc-url
      - ws://node:9944
      - --ws-server-listen-addr
      - 0.0.0.0:9955
      - --listen-on
      - /ip4/0.0.0.0/tcp/40333
      - --reward-address
      - 5Co1PCj2ivUiLiuJfd9USaiG7mSDLAzXAQ1KWxLDPqqZFhom
      - --plot-size
      - 10G
    user: root
    ports:
      - 30113:40333
    volumes:
      - farmer-data:/var/subspace
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.name == node2
      resources:
        reservations:
          memory: 32M
  node:
    image: ghcr.io/subspace/node:gemini-2a-2022-sep-10
    command:
      - --chain
      - gemini-2a
      - --base-path
      - /var/subspace
      - --execution
      - wasm
      - --state-pruning
      - "1024"
      - --keep-blocks
      - "1024"
      - --port
      - "30333"
      - --rpc-cors
      - all
      - --ws-port
      - "9944"
      - --rpc-methods
      - unsafe
      - --unsafe-ws-external
      - --validator
      - --name
      - swarm-node-mina
    user: root
    healthcheck:
      interval: 30s
      timeout: 5s
      retries: 5
    ports:
      - 30114:30333
    volumes:
      - node-data:/var/subspace
    networks:
      - net
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.labels.name == node2
      resources:
        reservations:
          memory: 32M
networks:
  bridgess:
    external: true
  net:
    driver: overlay
volumes:
  farmer-data:
  node-data: