version: "3.7"
services:
  node:
    image: ghcr.io/subspace/node:gemini-2a-2022-sep-10
    volumes:
      - node-data:/var/subspace:rw
    privileged: true
    user: root
    ports:
      # port
      - "0.0.0.0:port:30333"
      - "0.0.0.0:port:9944"

    restart: unless-stopped
    command:
      [
        "--chain",
        "gemini-2a",
        "--base-path",
        "/var/subspace",
        "--execution",
        "wasm",
        "--state-pruning",
        "1024",
        "--keep-blocks",
        "1024",
        "--port",
        "30333",
        "--rpc-cors",
        "all",
        "--rpc-methods",
        "unsafe",
        "--unsafe-ws-external",
        "--validator",
        "--name",
        # node name
        "name",
      ]
    networks:
      - swarm-node-net
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          memory: 32M
      placement:
        constraints:
          - node.labels.ssd == true

volumes:
  node-data:

networks:
  swarm-node-net: