apiVersion: v1
kind: StatefulSet
metadata:
  name: {{.Values.node.name}}
  labels:
    app: {{.Values.node.name}}
spec:
  replicas: 1
  serviceName: {{.Values.node.name}}
  selector:
    matchLabels:
      app: {{.Values.node.name}}
  template:
    metadata:
      labels:
        app: {{.Values.node.name}}
    spec:
      securityContext:
        fsGroup: 0
        runAsUser: 0
        runAsGroup: 0

      containers:
        - name: {{.Values.node.name}}
          image: {{.Values.image.node}}:{{.Values.image.tag}}
          ports:
            - containerPort: 9944
            - containerPort: 30333
          command:
            - /subspace-node
            - --chain
            - gemini-2a
            - --base-path
            - /var/subspace
            - --execution
            - wasm
            - --state-pruning
            - "1024"
            - --keep-blocks
            - "1024"
            - --port
            - "30333"
            - --rpc-cors
            - all
            - --ws-port
            - "9944"
            - --rpc-methods
            - unsafe
            - --unsafe-ws-external
            - --validator
            - --name
            - swarm-node-mina
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: "/var/subspace"
              name: {{.Values.node.name}}-pv-storage
        - name: {{.Values.node.name}}-farmer
          image:  {{.Values.image.farmer}}:{{.Values.image.tag}}
          ports:
            - containerPort: 40333
          command:
            - /subspace-farmer
            - --base-path
            - /var/subspace
            - farm
            - --node-rpc-url
            - ws://localhost:9944
            - --ws-server-listen-addr
            - 0.0.0.0:9955
            - --listen-on
            - /ip4/0.0.0.0/tcp/40333
            - --reward-address
            - st6Vn7LoygJKLrB6jrEk4mUw3qAQBVDqigjmMyLYN9zJnkGUk
            - --plot-size
            - 10G
          resources:
            requests:
              ephemeral-storage: "10Gi"
            limits:
              ephemeral-storage: "11Gi"

          volumeMounts:
            - name: {{.Values.node.name}}-farmer-data
              mountPath: "/var/subspace"

      volumes:
        - name: {{.Values.node.name}}-farmer-data
          emptyDir: {}
        - name: {{.Values.node.name}}-pv-storage
          persistentVolumeClaim:
            claimName: {{.Values.node.name}}-pv-claim

