---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.node.name}}-pv-claim
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
